// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhbvpfksbltrqpvptwtm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoYnZwZmtzYmx0cnFwdnB0d3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNTI4MzMsImV4cCI6MjA2NjkyODgzM30.CNU4xyD9npVNtcJdnkPMbTDJt-ruiYWG9a_wKMGTWuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});